version: '3'
services:
  rabbit1:
    image: rabbitmq:3.8.2
    container_name: rabbit1
    hostname: "rabbit1"
    restart: unless-stopped
    tty: true
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: alpine:3.11.3
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/app
    entrypoint: ./video-stream-conv
    volumes:
      - ./video:/var/app/video
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: DockerfileWorker
    image: jrottenberg/ffmpeg:4.1-ubuntu
    container_name: worker
    restart: unless-stopped
    tty: true
    working_dir: /var/app
    entrypoint: ./worker
    volumes:
      - ./video:/var/app/video
    networks:
      - app-network

  webserver:
    image: nginx:stable-alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./video:/var/app/video
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local